services:
  web:
    build: .
    container_name: zungat_tm_web

    volumes:
      - /var/www/zungat_tm:/app/staticfiles
      - ./data:/app/data

    restart: always

    environment:
      - DJANGO_SETTINGS_MODULE=zungat_tm.settings
      - PYTHONUNBUFFERED=1

    command: gunicorn --bind 0.0.0.0:8000 --workers 1 zungat_tm.wsgi:application

    ports:
      - "9010:8000"
