# Generated by Django 6.0.5 on 2026-05-18 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BitrixAuth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('long_token', models.CharField(max_length=255, null=True)),
                ('domain', models.CharField(max_length=255, null=True)),
                ('client_id', models.CharField(max_length=255, null=True)),
                ('client_secret', models.CharField(max_length=255, null=True)),
                ('redirect_uri', models.CharField(max_length=255, null=True)),
                ('refresh_token', models.CharField(max_length=2000, null=True)),
                ('access_token', models.CharField(max_length=2000, null=True)),
                ('refresh_token_expires', models.DateTimeField(null=True)),
                ('access_token_expires', models.DateTimeField(null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Аутентификационные данные Bitrix24',
                'verbose_name_plural': 'Аутентификационные данные Bitrix24',
            },
        ),
    ]
