# Generated by Django 6.0.5 on 2026-06-29 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArrestedDeposit',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('operation_id', models.IntegerField(unique=True)),
                ('available_funds', models.FloatField(default=0.0)),
            ],
        ),
    ]
