# Generated by Django 6.0.5 on 2026-06-30 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('depositarrest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='arresteddeposit',
            name='fact_payments',
            field=models.JSONField(default={}),
        ),
    ]
