# Generated by Django 6.0.5 on 2026-06-30 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('depositarrest', '0002_arresteddeposit_fact_payments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arresteddeposit',
            name='fact_payments',
            field=models.JSONField(default=dict),
        ),
    ]
