# Generated by Django 6.0.5 on 2026-06-30 07:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('depositarrest', '0003_alter_arresteddeposit_fact_payments'),
    ]

    operations = [
        migrations.AddField(
            model_name='arresteddeposit',
            name='deposit_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
