# Generated by Django 6.0.5 on 2026-06-30 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('depositarrest', '0004_arresteddeposit_deposit_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='arresteddeposit',
            name='driver_id',
            field=models.IntegerField(default=999999999, unique=True),
            preserve_default=False,
        ),
    ]
