# Generated by Django 6.0.5 on 2026-06-30 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('depositarrest', '0005_arresteddeposit_driver_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arresteddeposit',
            name='driver_id',
            field=models.IntegerField(),
        ),
    ]
