# Generated by Django 6.0.5 on 2026-06-30 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('depositarrest', '0006_alter_arresteddeposit_driver_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='arresteddeposit',
            old_name='available_funds',
            new_name='_available_funds',
        ),
    ]
