# Generated by Django 6.0.5 on 2026-07-02 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('depositarrest', '0007_rename_available_funds_arresteddeposit__available_funds'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arresteddeposit',
            name='_available_funds',
            field=models.FloatField(),
        ),
    ]
